services:
  product-service:
    build: ./productservice
    container_name: product_service
    depends_on:
      - postgres
    environment:
      SPRING_R2DBC_URL: r2dbc:postgresql://postgres:5432/productdb
      SPRING_R2DBC_USERNAME: user
      SPRING_R2DBC_PASSWORD: pass
    ports:
      - "8080:8080"
    networks:
      - product_network

  postgres:
    image: postgres
    container_name: product_db
    environment:
      POSTGRES_DB: productdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    networks:
      - product_network

  microfrontend-home:
    build:
      context: ./microfrontends/home
      dockerfile: Dockerfile
    container_name: mfe_home
    ports:
      - "5173:5173"
    networks:
      - product_network

  microfrontend-products:
    build:
      context: ./microfrontends/products
      dockerfile: Dockerfile
    container_name: mfe_products
    ports:
      - "5174:5174"
    networks:
      - product_network

networks:
  product_network:
    driver: bridge
