services:
  host:
    build:
      context: ./microfrontends/host
    ports:
      - "5173:80"

  remote-search:
    build:
      context: ./microfrontends/search
    ports:
      - "5175:5175"

networks:
  product_network:
    driver: bridge
  nexus_shared_net:
    external: true
