services:
  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    environment:
      - NEXUS_SECURITY_RANDOMPASSWORD=false
      - NEXUS_SECURITY_INITIAL_PASSWORD=admin123
    ports:
      - "8088:8081"

    networks:
      - nexus_shared_net

  nexus-setup:
    build:
      context: .
      dockerfile: Dockerfile-SetupNexus
    volumes:
      - ./scripts:/scripts
    working_dir: /scripts
    entrypoint: ["sh"]
    command: ["-c", "./setup-nexus.sh"]
    networks:
      - nexus_shared_net

  builder:
    image: maven:3.9-eclipse-temurin-17
    container_name: shared-builder
    depends_on:
      - nexus-setup
    working_dir: /build
    volumes:
      - ./shared/java/contracts:/build
      - ./settings.xml:/root/.m2/settings.xml
    entrypoint: ["/bin/sh", "-c"]
    command: [
        "echo '⏳ Waiting for Nexus...' &&
        sleep 30 &&
        mvn clean deploy -DskipTests",
      ]
    networks:
      - nexus_shared_net

networks:
  nexus_shared_net:
    driver: bridge
