spring:
  application:
    name: proudcts-query
  data:
    mongodb:
      uri: mongodb://mongo:27017/productsdb
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
        group-id: ${KAFKA_CONSUMER_GROUP_ID}
server:
  port: 8081
